infrastructure:
  - .github/**/*
  - pyproject.toml
  - Makefile
  - Dockerfile
  - docker-compose.yml

documentation:
  - "**/*.md"
  - references/**/*

testing:
  - tests/**/*
  - pytest.ini
  - .coveragerc

source:
  - scripts/**/*.py
